export const artist = {
  name: "Hina Bhatt",
  dob: "15th December 1970",
  email: "hina.bhatt@yahoo.com",
  phone: "+91 9766927455",
  address: "F-704, Lunkad Sky Lounge, Lane 7, Kalyaninagar, Pune - 411006, Maharashtra, India",
  statement:
    "Nature has always been my greatest source of inspiration and reflection. Its ever-changing light, colours, and moods speak to the rhythm of life itself. Through my work, I explore our intimate connection with the universe—the bonds between man, nature, and the divine. My paintings move between abstraction and emotion, expressing the energies, textures, and spiritual undercurrents that flow through existence. Each brushstroke becomes a meditation on harmony, transformation, and the quiet truths that nature reveals when we pause, observe, and allow ourselves to feel deeply.",
  ruturajStatement:
    "Ruturaj celebrates spring as a symbol of renewal, abundance, and divine joy. Inspired by Krishna's words, these works reflect the blossoming of life both in nature and within the self. Each painting is a meditation on harmony—with the eternal, with nature, and with one's inner being. Though seasons may change, a spirit connected to the divine remains in perpetual bloom—radiant, grateful, and full of grace.",
};

export const resume = {
  education: [
    { title: "Bachelor of Fine Arts", inst: "Stella Maris College, Chennai (1991)", type: "Graduation" },
    { title: "Diploma in Textile Designing", inst: "Nirmala Niketan Mumbai (1993)", type: "Diploma" },
    { title: "Management of Social Initiatives", inst: "IIM Kozhikode", type: "MDP" },
  ],
  awards: ["Gold Award at Sumbaran Art Foundation"],
  soloShows: "7 Solo Exhibitions (Pune, Mumbai)",
  groupShows:
    "40+ Group Shows in India and Abroad (Chennai, Mumbai, Bangalore, Pune, Dubai, Doha, New Delhi, Lucknow, Ahmedabad, Varanasi)",
  collections: [
    "Lakshya Outdoor Media",
    "MD - JP Morgan",
    "CEO, Bajaj Finance",
    "Rahi Platform Technologies",
    "Yoga Centre - Mumbai",
    "Many private collectors in India and abroad",
  ],
};

export interface Artwork {
  id: number;
  title: string;
  size: string;
  medium: string;
  price: string;
  color: string;
  image: string;
  extra?: string;
}

export const collections: Record<string, Artwork[]> = {
  ruturaj: [
    {
      id: 1,
      title: "Ruturaj-1",
      size: "24 × 24 inches",
      medium: "Oil on Canvas",
      price: "Price on Request",
      color: "bg-amber-100",
      image: "/images/ruturaj/ruturaj-1.jpg",
    },
    {
      id: 2,
      title: "Ruturaj-7",
      size: "36 × 36 inches",
      medium: "Oil on Canvas",
      price: "Price on Request",
      color: "bg-orange-100",
      image: "/images/ruturaj/ruturaj-7.jpg",
    },
    {
      id: 3,
      title: "Ruturaj-15",
      size: "24 × 24 inches",
      medium: "Oil on Canvas",
      price: "Price on Request",
      color: "bg-yellow-100",
      image: "/images/ruturaj/ruturaj-15.jpg",
    },
    {
      id: 4,
      title: "Ruturaj-23",
      size: "60 × 36 inches",
      medium: "Oil on Canvas",
      price: "Price on Request",
      color: "bg-rose-100",
      image: "/images/ruturaj/ruturaj-23.jpg",
    },
    {
      id: 5,
      title: "Ruturaj-39",
      size: "60 × 36 inches",
      medium: "Oil on Canvas",
      price: "Price on Request",
      color: "bg-red-50",
      image: "/images/ruturaj/ruturaj-39.jpg",
    },
    {
      id: 6,
      title: "Ruturaj-43",
      size: "36 × 36 inches",
      medium: "Oil on Canvas",
      price: "Price on Request",
      color: "bg-emerald-50",
      image: "/images/ruturaj/ruturaj-43.jpg",
    },
    {
      id: 7,
      title: "Ruturaj-48",
      size: "36 × 36 inches",
      medium: "Oil on Canvas",
      price: "Price on Request",
      color: "bg-teal-50",
      image: "/images/ruturaj/ruturaj-48.jpg",
    },
    {
      id: 8,
      title: "Ruturaj-53",
      size: "30 × 30 inches",
      medium: "Oil on Canvas",
      price: "Price on Request",
      color: "bg-blue-50",
      image: "/images/ruturaj/ruturaj-53.jpg",
    },
    {
      id: 9,
      title: "Ruturaj-54",
      size: "30 × 30 inches",
      medium: "Oil on Canvas",
      price: "Price on Request",
      color: "bg-indigo-50",
      image: "/images/ruturaj/ruturaj-54.jpg",
    },
    {
      id: 10,
      title: "Ruturaj-56",
      size: "30 × 30 inches",
      medium: "Oil on Canvas",
      price: "Price on Request",
      color: "bg-violet-50",
      image: "/images/ruturaj/ruturaj-56.jpg",
    },
    {
      id: 11,
      title: "Ruturaj-61",
      size: "24 × 48 inches (Diptych)",
      medium: "Oil on Canvas",
      price: "Price on Request",
      extra: "Total: 16 sq. ft",
      color: "bg-purple-100",
      image: "/images/ruturaj/ruturaj-61.jpg",
    },
  ],
  rootsAndBonds: [
    {
      id: 201,
      title: "Roots and Bonds - 1",
      size: "24 x 23 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-1.jpg",
    },
    {
      id: 202,
      title: "Roots and Bonds - 2",
      size: "18 x 18 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-2.jpg",
    },
    {
      id: 203,
      title: "Roots and Bonds - 3",
      size: "18 x 18 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-3.jpg",
    },
    {
      id: 204,
      title: "Roots and Bonds - 4",
      size: "18 x 18 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-4.jpg",
    },
    {
      id: 205,
      title: "Roots and Bonds - 5",
      size: "12 x 24 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-5.jpg",
    },
    {
      id: 206,
      title: "Roots and Bonds - 6",
      size: "13 x 16 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-6.jpg",
    },
    {
      id: 207,
      title: "Roots and Bonds - 7",
      size: "13 x 16 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-7.jpg",
    },
    {
      id: 208,
      title: "Roots and Bonds - 8",
      size: "24 x 36 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-8.jpg",
    },
    {
      id: 209,
      title: "Roots and Bonds - 9",
      size: "24 x 24 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-9.jpg",
    },
    {
      id: 210,
      title: "Roots and Bonds - 10",
      size: "24 x 36 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-10.jpg",
    },
    {
      id: 211,
      title: "Roots and Bonds - 11",
      size: "24 x 24 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-11.jpg",
    },
    {
      id: 212,
      title: "Roots and Bonds - 12",
      size: "24 x 24 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-12.jpg",
    },
    {
      id: 213,
      title: "Roots and Bonds - 13",
      size: "24 x 48 Inches",
      medium: "Mix Media on Canvas",
      price: "Price on Request",
      color: "bg-stone-200",
      image: "/images/roots-and-bonds/roots-bonds-13.jpg",
    },
  ],
};
